# Generated by Django 3.0.7 on 2020-09-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='exDate',
            new_name='expireDate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='mDate',
            new_name='madeDate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pDes',
            new_name='productDescription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pName',
            new_name='productName',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='status_of_product',
            field=models.CharField(choices=[('In stock', 'In stock'), ('Out of stock', 'Out of stock')], default='In stock', max_length=15),
        ),
    ]
