# Generated by Django 3.0.7 on 2020-09-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('taka', 'taka'), ('rupe', 'rupe')], default='taka', max_length=6),
        ),
    ]
