# Generated by Django 3.0.7 on 2020-10-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Medicine', 'Medicine'), ('Food', 'Food'), ('Fashion', 'Fashion')], default='Medicine', max_length=10),
        ),
    ]
