# Generated by Django 3.0.7 on 2020-11-03 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('Bemail', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('pid', models.IntegerField(max_length=5)),
                ('quantity', models.IntegerField(max_length=5)),
                ('address', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=30)),
                ('prname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
    ]
