# Generated by Django 3.0.7 on 2020-11-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201104_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pid',
            field=models.CharField(max_length=3),
        ),
    ]
