# Generated by Django 3.0.7 on 2020-11-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201104_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Bemail',
            field=models.EmailField(max_length=30),
        ),
    ]
