# Generated by Django 3.0.7 on 2020-11-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201104_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pid',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(max_length=3),
        ),
    ]
