# Generated by Django 3.1.3 on 2020-11-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20201115_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
